### PR TITLE
[MODINVOICE-135] Removed invoice number from invoiceLineNumber

### PR DESCRIPTION
**Pull request by damien-git**
## Purpose
[MODINVOICE-135](https://issues.folio.org/browse/MODINVOICE-135)

## Approach
- Updated invoice line number generation to use only the sequence number.
- Updated sort by line number to support both formats until invoice lines have been migrated.
- Updated a test and mock data.

#### TODOS and Open Questions
Is there is a test of prorated adjustments affecting multiple invoice lines somewhere? I didn't see any, but it would rely on the sort.

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Comment by damien-git** [comment]
Screenshot_20210219_140806

**Comment by damien-git** [comment]
Screenshot_20210219_141107

**Comment by grabsefx** [comment]
looks good. Could you make this changes for the examples in acq-model?
https://github.com/folio-org/acq-models/blob/master/mod-invoice-storage/examples/invoice_line.sample#L55
https://github.com/folio-org/acq-models/blob/master/mod-invoice-storage/examples/invoice_line_collection.sample#L38

**Review by grabsefx — APPROVED** [review]

**Review by KreiDer — APPROVED** [review]

**Comment by damien-git** [comment]
@grabsefx 
> looks good. Could you make these changes for the examples in acq-model?

Yes, but there are sample files using invoiceLineNumber in other projects as well. I will modify all of them for consistency.

**Pull request merged**
