### PR TITLE
[MODINVOICE-533] - Change restricted expenditures calculations

### PR DESCRIPTION
**Pull request by Abdulkhakimov**
## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate action.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code are 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added, or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all the appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally, all the PRs involved in breaking changes would be merged on the same day
to avoid breaking the folio-testing environment.
Communication is paramount if that is to be achieved,
especially as the number of inter-module and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems,
ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Review by imerabishvili — APPROVED** [review]

**Comment by damien-git** [comment]
@Abdulkhakimov The change looks good but I think we might have to revert [MODINVOICE-367](https://folio-org.atlassian.net/browse/MODINVOICE-367) in this PR. The current calculation when `totalAmountCanBeExpended.subtract(unavailable).isNegative()`, checking that `-totalAmountCanBeExpended > 0` makes no sense to me.

**Comment by damien-git** [comment]
I don't understand what `calculateNewExpendedAmount()` and `newExpendedAmount.isGreaterThan(amountCanBeExpended)` are for, and I am wondering if we can remove that... Normally we should just have to check that the pending payment changes do not make the total expenses go beyond the limit. `afterApproveExpended.isGreaterThan(totalAmountCanBeExpended)` is already doing that (note: `totalAmountCanBeExpended` is not the total for the invoice but the difference with the previous version).

**Comment by Abdulkhakimov** [comment]
@damien-git Thank you for investigation. Changed follow by your comments. Please review it again

**Comment by damien-git** [comment]
> @damien-git Thank you for investigation. Changed follow by your comments. Please review it again

Thanks. We'll have to check it works as expected, but this is much easier to understand like that.

**Review by damien-git — APPROVED** [review]

**Comment by Abdulkhakimov** [comment]
integration tests are passed: 
image

**Pull request merged**
